on:
  push:
jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
     - name: create vars
       uses: actions/checkout@v3
     - name: craete variables
       run: |
        V=$(grep "plugin->version" version.php | cut -d '=' -f2 | cut -d ' ' -f2 | cut -d ';' -f1)
        N=$(grep "component" version.php | cut -d "'" -f2)
        echo "NV=$(echo $N"_"$V)" >> $GITHUB_ENV
     - name: show vars
       run: echo ${{ env.NV }}
    
